### ISSUE TITLE
Where in HACS ?

### ISSUE THREAD

**Issue by oywino** [thomasloven/hass-config#11]
I hoped I would find your custom plug-in in HACS named "Lovelace-card-mod"  but I'm not able to find it anywhere?
You did say initially that you recommend using HACS ?  So, where in HACS is it?

**Comment by oywino** [comment]
It would have been great to at least have an answer ?

**Comment by a-macedo** [comment]
It can be found in HACS - **Frontend** integration by the name `slider-entity-row`
