### ISSUE TITLE
Clock Card working fine when HA used with browser, but not with HA app (HA-companion 2021.12)

### ISSUE THREAD

**Issue by michael5411** [thomasloven/hass-config#18]
That's the problem in a few words: Everything is working fine, when HA is used with Chrome browser. 
My HA-Version: core-2021.12.8, supervisor-2021.12.2, Home Assistant OS 7.1

When using to **Home Assistant Companion 2021.12 (2021.322)** there is no error message, but it does not show time or date.

Any idea, what could be wrong? It's only with the **clock card** implementation.
All other HACS-integrations are working fine.

**Comment by michael5411** [comment]
solved

**Comment by vinisxs** [comment]
> solved

@michael5411 
I'm having the same problem, how did you solve it?
