### ISSUE TITLE
what am i missing, i dont see this in HACS?

### ISSUE THREAD

**Issue by Menz01** [thomasloven/hass-config#24]
Hello. been watching all the video guides for this and they all show it being installed using HACS. i have HACS installed and have used it for quite a few installs already. however when i go in i do not see "auto-entities" as a choice. am i missing something?

**Comment by Menz01** [comment]
nevermind... i found it

**Comment by simondean** [comment]
@Menz01 how did you find it?  I'm facing the same issue

**Comment by simondean** [comment]
Ah, I've just realised how to find it.  You have to click the `Frontend` tab at the top of the HACS page in Home Assistant, in order to install frontend integrations
