### ISSUE TITLE
The layout tab not appearing for me

### ISSUE THREAD

**Issue by IIIdefconIII** [thomasloven/hass-config#32]
Yours
![image](https://github.com/thomasloven/hass-config/assets/9917659/5b36e77a-456c-484e-a280-03b7bfc4353d)

vs myne:
![image](https://github.com/thomasloven/hass-config/assets/9917659/7381b13b-008d-471e-8de8-0c09c5ca3f4b)

**Comment by mwilliams03** [comment]
I had exactly the same issue. clearing the browser cache fixed it

**Comment by IIIdefconIII** [comment]
> I had exactly the same issue. clearing the browser cache fixed it

Ill try that once more later this week thanks for the reply

**Comment by IIIdefconIII** [comment]
> I had exactly the same issue. clearing the browser cache fixed it

Dont tell people what to try if it has nothing to do with it

**Comment by thomasloven** [comment]
Look at the kettle calling the pot black.

What does this have to do with my personal (outdated) Home Assistant setup?

**Comment by IIIdefconIII** [comment]
> Look at the kettle calling the pot black.

hi, i wasnt sure i just hoped to get some support and i tought i might misconfigured something, sry thomas

**Comment by thomasloven** [comment]
You may have better luck in the layout-card repo. Or the forums.

**Comment by IIIdefconIII** [comment]
> You may have better luck in the layout-card repo. Or the forums.

thanks!

**Comment by IIIdefconIII** [comment]
#archive
