### ISSUE TITLE
Update to Clearing your browser cache Wiki

### ISSUE THREAD

**Issue by dsellers1** [thomasloven/hass-config#33]
Here's an update to the [Clearing your browser cache](https://github.com/thomasloven/hass-config/wiki/Clearing-your-browser-cache) Wiki. 

```markdown
### Google Chrome (and most Chromium-based browsers)
<details><summary>Windows & Mac</summary>

- At the top right, click More and then **Settings**
- Click the **Privacy and Security** tab on the right
- Click **Clear browsing data**
- Select the time range **All time**
- Uncheck *Browsing history* and *Cookies and other site data*
- With *Cached images and files* selected, click **Clear data**
- Close the Settings tab

</details><details><summary>Android</summary>

- At the top right, tap More and then **Settings**
- Tap **Privacy and Security**
- Tap **Clear browsing data**
- Select the time range **All time**
- Uncheck *Browsing history* and *Cookies and site data*
- With *Cached images and files* checked, tap **Clear data**
- If shown *Also clear data from these sites?*, select appropriately and tap **Clear**
- Tap **OK, got it** if notified of cleared data on synced devices
- Tap the Back arrow twice to close Settings

</details><details><summary>iOS</summary>

- Tap More and then **Clear Browsing Data**
- Uncheck *Browsing history* and *Cookies and site data*
- With *Cached images and files* checked, tap **Clear browsing data**
- At the top right, tap Done.

</details>

### Safari

<details><summary>Mac</summary>

- Navigate to the page
- Press <kbd>Option+Cmd+E</kbd> to clear the cache
- Press <kbd>Cmd+R</kbd> to reload the page

</details><details><summary>iOS</summary>

- Go to Settings > Safari > Advanced > Website Data
- Tap Remove All Website Data

</details>

### Microsoft Edge
<details><summary>Windows & Mac</summary>
  
- Click Menu (the three dots at the top right of the window) and select **Settings**
- Click the **Privacy, search and services** pane
- In the *Clear browsing data* section, click **Choose what to clear**
- Select Time Range of **All time**
- Uncheck everything except *Cached images and files*
- Click **Clear now**
- Close the Settings tab

</details><details><summary>Android</summary>
  
- Tap Menu (the three dots at the bottom of the screen), and select **Settings**
- Tap **Privacy and Security**
- Tap **Clear browsing data**
- Uncheck everything except *Cached images and files*
- Tap **Clear data**
- Press the Back arrow twice to exit Settings

</details>
  
### Firefox

<details><summary>Windows & Mac</summary>

- Click the Menu button and select **Settings**
- Select the **Privacy and Security** pane
- In the *Cookies and Site Data* section, click **Clear Data**
- Uncheck *Cookies and Site Data*
- With *Cached Web Content* checked, click **Clear**
- Close the Settings tab

</details><details><summary>Android</summary>

- Tap Menu (the three dots at the bottom of the screen), and select **Settings**
- Tap **Delete browsing data**
- Uncheck everything except *Cached images and files*
- Tap **Delete browsing data**
- Tap **Delete**
- Press the Back arrow twice to close the Settings

</details><details><summary>iOS</summary>

- At the bottom of the screen, tap the menu button
- Tap **Settings**
- Under the *Privacy* section, tap **Data Management**
- Tap **Website Data**
- Tap the site you want to clear or select Show More to find the site you want to clear
- At the bottom of the list, select **Clear Items**

</details>

### Home Assistant Companion App 

<details><summary>Android</summary>

- Go to **Settings**
- Tap **Apps**
- Tap **Home Assistant**
- Tap **Storage**
- Tap **Clear cache**
- Tap the Back arrow
- Tap **Force stop** and **OK**
- Tap **Open** to reopen the app

</details><details><summary>iOS</summary>
  
- Go to Home Assistant Settings
- Select **Companion App** (near the bottom)
- Select **Debugging** (at the bottom)
- Tap **Reset Frontend Cache**

</details>

### Fully Kiosk Browser

<details><summary>Amazon Fire</summary>

- Exit Fully Kiosk Browser (swipe from the left side of the screen and tap **Exit Fully**, confirming if asked)
- Go to **Settings** for the tablet (swipe down from the top of the screen twice and tap the Gear icon)
- Tap **Apps & Notifications**
- Tap **Fully Kiosk Browser** (or **See all xx apps** if not listed in Recently opened apps)
- Tap **Storage**
- Tap **Clear cache**
- Close Settings
- Reopen Fully Kiosk Browser

</details><details><summary>Android</summary>

- Exit Fully Kiosk Browser (swipe from the left side of the screen and tap **Exit Fully**, confirming if asked)
- Go to **Settings** for the tablet (swipe down from the top of the screen and tap the Gear icon)
- Tap **Apps**
- Tap **Fully Kiosk Browser**
- Tap **Storage**
- Tap **Clear cache**
- Close Settings
- Reopen Fully Kiosk Browser

</details>
```
### Google Chrome (and most Chromium-based browsers)
<details><summary>Windows & Mac</summary>

- At the top right, click More and then **Settings**
- Click the **Privacy and Security** tab on the right
- Click **Clear browsing data**
- Select the time range **All time**
- Uncheck *Browsing history* and *Cookies and other site data*
- With *Cached images and files* selected, click **Clear data**
- Close the Settings tab

</details><details><summary>Android</summary>

- At the top right, tap More and then **Settings**
- Tap **Privacy and Security**
- Tap **Clear browsing data**
- Select the time range **All time**
- Uncheck *Browsing history* and *Cookies and site data*
- With *Cached images and files* checked, tap **Clear data**
- If shown *Also clear data from these sites?*, select appropriately and tap **Clear**
- Tap **OK, got it** if notified of cleared data on synced devices
- Tap the Back arrow twice to close Settings

</details><details><summary>iOS</summary>

- Tap More and then **Clear Browsing Data**
- Uncheck *Browsing history* and *Cookies and site data*
- With *Cached images and files* checked, tap **Clear browsing data**
- At the top right, tap Done.

</details>

### Safari

<details><summary>Mac</summary>

- Navigate to the page
- Press <kbd>Option+Cmd+E</kbd> to clear the cache
- Press <kbd>Cmd+R</kbd> to reload the page

</details><details><summary>iOS</summary>

- Go to Settings > Safari > Advanced > Website Data
- Tap Remove All Website Data

</details>

### Microsoft Edge
<details><summary>Windows & Mac</summary>
  
- Click Menu (the three dots at the top right of the window) and select **Settings**
- Click the **Privacy, search and services** pane
- In the *Clear browsing data* section, click **Choose what to clear**
- Select Time Range of **All time**
- Uncheck everything except *Cached images and files*
- Click **Clear now**
- Close the Settings tab

</details><details><summary>Android</summary>
  
- Tap Menu (the three dots at the bottom of the screen), and select **Settings**
- Tap **Privacy and Security**
- Tap **Clear browsing data**
- Uncheck everything except *Cached images and files*
- Tap **Clear data**
- Press the Back arrow twice to exit Settings

</details>
  
### Firefox

<details><summary>Windows & Mac</summary>

- Click the Menu button and select **Settings**
- Select the **Privacy and Security** pane
- In the *Cookies and Site Data* section, click **Clear Data**
- Uncheck *Cookies and Site Data*
- With *Cached Web Content* checked, click **Clear**
- Close the Settings tab

</details><details><summary>Android</summary>

- Tap Menu (the three dots at the bottom of the screen), and select **Settings**
- Tap **Delete browsing data**
- Uncheck everything except *Cached images and files*
- Tap **Delete browsing data**
- Tap **Delete**
- Press the Back arrow twice to close the Settings

</details><details><summary>iOS</summary>

- At the bottom of the screen, tap the menu button
- Tap **Settings**
- Under the *Privacy* section, tap **Data Management**
- Tap **Website Data**
- Tap the site you want to clear or select Show More to find the site you want to clear
- At the bottom of the list, select **Clear Items**

</details>

### Home Assistant Companion App 

<details><summary>Android</summary>

- Go to **Settings**
- Tap **Apps**
- Tap **Home Assistant**
- Tap **Storage**
- Tap **Clear cache**
- Tap the Back arrow
- Tap **Force stop** and **OK**
- Tap **Open** to reopen the app

</details><details><summary>iOS</summary>
  
- Go to Home Assistant Settings
- Select **Companion App** (near the bottom)
- Select **Debugging** (at the bottom)
- Tap **Reset Frontend Cache**

</details>

### Fully Kiosk Browser

<details><summary>Amazon Fire</summary>

- Exit Fully Kiosk Browser (swipe from the left side of the screen and tap **Exit Fully**, confirming if asked)
- Go to **Settings** for the tablet (swipe down from the top of the screen twice and tap the Gear icon)
- Tap **Apps & Notifications**
- Tap **Fully Kiosk Browser** (or **See all xx apps** if not listed in Recently opened apps)
- Tap **Storage**
- Tap **Clear cache**
- Close Settings
- Reopen Fully Kiosk Browser

</details><details><summary>Android</summary>

- Exit Fully Kiosk Browser (swipe from the left side of the screen and tap **Exit Fully**, confirming if asked)
- Go to **Settings** for the tablet (swipe down from the top of the screen and tap the Gear icon)
- Tap **Apps**
- Tap **Fully Kiosk Browser**
- Tap **Storage**
- Tap **Clear cache**
- Close Settings
- Reopen Fully Kiosk Browser

</details>

**Comment by thomasloven** [comment]
Thanks a lot!
I've updated the wiki.
