### ISSUE TITLE
Documentation suggestion

### ISSUE THREAD

**Issue by RichardUUU** [thomasloven/hass-config#4]
Thomas, I really appreciate everything you do regarding Home Assistant. Here's a small suggestion for your Misc tricks page: 

Under Node anchors you have:
```
# When you write:
key: &anchor value
```
That threw me for a bit, because it doesn't tell me WHY. Perhaps you could change it to: 
```
# To define an anchor:
key: &anchor value
```
Same thing with Merge keys: # To define a key

Cheers, Richard

**Comment by pinkfloydFR** [comment]
And can you add example for :  
    restriction-success-lock-color:
    restriction-regular-lock-color:

i can't make it work :(
